os: linux
files:
  - source: /
    destination: /opt/devops/frontend
hooks:
  ApplicationStop:
    - location: docker-scripts/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: docker-scripts/start.sh
      timeout: 300
      runas: root
