version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 891377328182.dkr.ecr.us-east-1.amazonaws.com/ecr-devops-frontend
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t frontend-image .
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag frontend-image:latest 891377328182.dkr.ecr.us-east-1.amazonaws.com/ecr-devops-frontend:latest
      - docker push 891377328182.dkr.ecr.us-east-1.amazonaws.com/ecr-devops-frontend:latest

artifacts:
  files:
    - '**/*'
  discard-paths: yes
